In [1]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [2]:
a = np.array([[1.5,0],[0,3.0]])
a

array([[ 1.5,  0. ],
       [ 0. ,  3. ]])

In [3]:
a = np.zeros(4)
a

array([ 0.,  0.,  0.,  0.])

In [4]:
a = np.ones(3)
a

array([ 1.,  1.,  1.])

In [5]:
a = np.ones((3,4))
a

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [6]:
a = np.empty((3,2))
a

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [7]:
a = np.identity(5)
a

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [25]:
a = np.array([1.3,2.4,4.1])
a = np.array(a , dtype=float)
a.astype(int)
print(a.flags)
print(a.strides)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
(8,)


In [28]:
a = np.eye(4,2)
a

array([[ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [30]:
a = np.arange(1,2,0.3)
a

array([ 1. ,  1.3,  1.6,  1.9])

In [36]:
a = np.linspace(1,2,4)
a

array([ 1.        ,  1.33333333,  1.66666667,  2.        ])

In [37]:
a = np.logspace(1,3,3)
a

array([   10.,   100.,  1000.])

In [40]:
a = np.logspace(1,3,3,base=5)
a

array([   5.,   25.,  125.])

In [41]:
a = np.tile([0,1,2,3],3)
a

array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3])

In [48]:
a,b = np.meshgrid([1,2],[4,5,6,7,8])
print(a)
print(b)

[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [1 2]]
[[4 4]
 [5 5]
 [6 6]
 [7 7]
 [8 8]]


In [49]:
a = np.tri(3)
a

array([[ 1.,  0.,  0.],
       [ 1.,  1.,  0.],
       [ 1.,  1.,  1.]])

In [50]:
a = np.diag([[0,1],[3,4]])
a

array([0, 4])

In [53]:
a = np.empty(4)
a

array([ 1.        ,  1.33333333,  1.66666667,  2.        ])

In [54]:
a = np.diag([[0,1],[3,4]])
a

array([0, 4])

In [57]:
b = a.copy()
b[0]=5
a

array([0, 4])

In [61]:
a = np.random.randint(0,1e5,10)
a

array([86621, 56232, 30482, 78487, 93987, 53409, 91892, 62225, 91108, 84898])

In [64]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
b = a.reshape((2,5))
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [70]:
b = a.resize((5,2))
print(b)
a

None


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [81]:
a = np.arange(10)
a.resize(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [82]:
a.resize(11)
a

ValueError: cannot resize an array that references or is referenced
by another array in this way.  Use the resize function

In [83]:
a = np.arange(10)
a.resize(12,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [9, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])